service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get